spring:
  profiles:
    active:
    - test

---

spring:
  profiles: test
name: test-YAML
environment: testing
enabled: false
servers:
  - www.abc.test.com
  - www.xyz.test.com
  
external: [www.abc.test.com, www.xyz.test.com]

map:
  firstkey: key1
  secondkey: key2
  
component:
  idm:
    url: myurl
    user: user
    password: password
    description: >
      this should be a long
      description
  service:
    url: myurlservice
    token: token
    description: >
      this should be another long
      description
---

spring:
  profiles: prod
name: prod-YAML
environment: production
enabled: true
servers:
  - www.abc.com
  - www.xyz.com
    
---

spring:
    profiles: dev
name: ${DEV_NAME:dev-YAML}
environment: development
enabled: true
servers:
    - www.abc.dev.com
    - www.xyz.dev.com
