server:
   port: 8081
keycloak:
  auth-server-url: http://localhost:8080 # Keycloak server url
  realm: SpringBootKeycloak # Keycloak Realm
  resource: login-app # Keycloak Client
  principal-attribute: preferred_username
  ssl-required: external
  credentials:
    secret: 00000000-0000-0000-0000-000000000000
  
spring:
   security:
      oauth2:
         resourceserver:
            jwt.issuer-uri: http://localhost:8080/realms/SpringBootKeycloak
   mvc:
      pathmatch:
            matching-strategy: ant_path_matcher
    
