swagger: "2.0"
info:
  description: "This is a sample Swagger description for an Array server"
  version: "1.0.0"
  title: "Swagger Array"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/localhost:8080/"
tags:
  - name: "foo-controller"
    description: "Foo controller"

paths:
  /foos:
    post:
      tags:
        - "foo-controller"
      summary: "create"
      description: ""
      parameters:
        - in: body
          description: ""
          required: true
          name: name
          schema:
            type: array
            items:
              type: string
            example: ["str1", "str2", "str3"]
      responses:
        default:
          description: OK 