server:
  port: 9001

logging:
  level:
    org.springframework.security: trace

spring:
  security:
    user:
      name: baeldung
      password: password
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "user-service"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
              scopes:
                - "openid"
                - "user.read"
              redirect-uris:
                - "http://localhost:8080/login/oauth2/code/user-service"
          token-exchange-client:
            registration:
              client-id: "token-exchange-client"
              client-secret: "{noop}token"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "urn:ietf:params:oauth:grant-type:token-exchange"
              scopes:
                - "openid"
                - "message.read"