version: '3.7'

services:
  zookeeper:
    restart: always
    image: zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper-volume"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - private_network

  kafka:
    restart: always
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - "kafka-volume"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_LISTENER_NAMES=PLAINTEXT,EXTERNAL
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    depends_on:
      - zookeeper
    networks:
      - private_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - network.host=0.0.0.0
      - ELASTIC_PASSWORD=Elasticsearch@123
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - private_network

  spring-boot-app:
    container_name: springbootapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - elasticsearch
    networks:
      - private_network


networks:
  private_network:
    driver: bridge

volumes:
  kafka-volume:
  zookeeper-volume:
  esdata1: