env:
  docker_tag: schalla/test:dev-0.0.7

# This is a basic workflow to help you get started with GitHub Actions 
name: Scan code using fd code scanner

# Triggers the workflow on push events but only for the development branch
on:
  push:
    branches: [ "master" ]
    
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

# Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3

    # Download image from docker hub

    - name: Download docker image
      run: docker pull "${{env.docker_tag}}" --platform=linux/arm64

    - name : check git status
      run: pwd; git rev-list --all
        
    - name: docker scan
      run: |
        docker run -e GITHUB_REPOSITORY_OWNER="${{github.repository_owner}}" \
          -e GITHUB_REPOSITORY_OWNER_ID="${{github.repository_owner_id}}" \
          -e GITHUB_REPOSITORY="${{github.repository}}" \
          -e GITHUB_REPOSITORY_ID="${{github.repository_id}}" \
          -e GITHUB_BASE_REF="${{github.base_ref}}" \
          -e GITHUB_EVENT_NAME="${{github.event_name}}" \
          -e GITHUB_ACTOR="${{github.actor}}" \
          -e GITHUB_ACTOR_ID="${{github.actor_id}}" \
          -e FD_API_KEY="${{secrets.FD_API_KEY}}" \
          -e GITHUB_TOKEN="${{github.token}}" \
          -e WORKSPACE_PATH="/src" \
          -e LOG_LEVEL="debug" \
          -v "${{ github.workspace }}":/src  "${{env.docker_tag}}"
